### ISSUE TITLE
Nginx OpenTracing to Elastic APM

### ISSUE THREAD

**Issue by danielwrayois** [opentracing-contrib/nginx-opentracing#121]
Hi,

I am looking to setup Nginx tracing and send the traces to an Elastic APM server, since the APM server is based upon the OpenTracing standards would the Jaeger, or Zipkin plugins work with this backend?

**Comment by jkowall** [comment]
You'd actually need to make code changes for the library. The way OpenTracing works is that is specifies the API needed to decorate the code and get tracing, but it doesn't specify a backend format. Each toolset has a different OpenTracing library. I haven't read through the code for this integration but they seem to have used libraries to support a few tools, namely Jaeger, Zipkin, LightStep, or DataDog. 

Elastic APM doesn't have a C++ SDK for OpenTracing, https://www.elastic.co/guide/en/apm/get-started/current/opentracing.html so it's not going to work for this implementation. However, the new standard OpenTelemetry has standard exporters for tools including Elastic APM, but this specific implementation hasn't been ported over yet since OpenTelemetry is not finalized yet. The short answer is you have to wait, but you may want to just instrument your app instead which has a lot more benefits than instrumenting a proxy IMO.

**Comment by miry** [comment]
If https://github.com/open-telemetry/opentelemetry-collector can support Elastic APM, then there is possobility to use any opentracing tracers and collector export traces to Elastic APM.

**Comment by sasah** [comment]
https://www.elastic.co/guide/en/apm/get-started/current/open-telemetry-elastic.html

**Comment by sasah** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticexporter

**Comment by sasah** [comment]
https://docs.nginx.com/nginx/admin-guide/dynamic-modules/opentracing/

**Comment by sasah** [comment]
https://github.com/opentracing-contrib/nginx-opentracing
