### ISSUE TITLE
Assets in github release are missing on v0.24.0

### ISSUE THREAD

**Issue by cbeauchesne** [opentracing-contrib/nginx-opentracing#257]
Regarding previous releases, the [v0.24.0](https://github.com/opentracing-contrib/nginx-opentracing/releases/tag/v0.24.0) have barely no built asset shipped.

We have a lot of stuff that rely on those assets. Could you tell me if it's expected, or if it's a bug in the release process?

**Comment by Tyler-2** [comment]
Reporting same, this broke our build process which is based on Datadog' documentations for getting opentracing on nginx.

https://github.com/DataDog/dd-opentracing-cpp/blob/master/examples/nginx-tracing/Dockerfile

In particular, this fails:
```
  wget https://github.com/opentracing-contrib/nginx-opentracing/releases/download/${OPENTRACING_NGINX_VERSION}/linux-amd64-nginx-${NGINX_VERSION}-ot16-ngx_http_module.so.tgz && \
```

Because the resulting path is invalid:
```
https://github.com/opentracing-contrib/nginx-opentracing/releases/download/v0.24.0/linux-amd64-nginx-1.18.0-ot16-ngx_http_module.so.tgz
```

And as stated this is because there are no assets here:
https://github.com/opentracing-contrib/nginx-opentracing/releases/

**Comment by lucacome** [comment]
Hi @cbeauchesne sorry about that. Apparently, a token expired in the pipeline that uploads the artifacts and I don't have access there, we need help from @miry or @rnburn I believe

**Comment by lucacome** [comment]
@cbeauchesne @Tyler-2 the assets are now in the release, sorry again for the inconvenience

**Comment by Tyler-2** [comment]
Thank you for your service! Will letcha know when I've updated our release.

**Comment by cbeauchesne** [comment]
Thanks a lot @lucacome

**Comment by lucacome** [comment]
Closing this since it was resolved

**Comment by Tyler-2** [comment]
Updated our release, all's well. Thanks for the quick fix!
